# Generated by Django 6.1.1 on 2026-10-08 15:54

import apps.prestamos.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
        ('usuarios', '0006_unir_ramas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('checklist_devolucion', models.JSONField(default=list)),
                ('resultado', models.JSONField(default=dict)),
                ('reporte', models.FileField(blank=True, help_text='PDF obligatorio cuando la devolución detecta daño (RN10).', null=True, upload_to=apps.prestamos.models.ruta_reporte, verbose_name='Reporte de daños (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion', to='prestamos.prestamo')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion', '-id'],
            },
        ),
    ]
