# Generated by Django 6.1.1 on 2026-09-23 00:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email (contacto)')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('tipo', models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('administrativo', 'Administrativo')], max_length=20)),
                ('rol', models.CharField(choices=[('prestatario', 'Prestatario'), ('gestor', 'Gestor de Almacén'), ('administrador', 'Administrador')], default='prestatario', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('reputacion_puntaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(500)], verbose_name='Puntaje de reputación')),
                ('reputacion_tier', models.CharField(choices=[('avanzado', 'Avanzado'), ('estandar', 'Estándar'), ('restringido', 'Restringido')], default='estandar', max_length=20, verbose_name='Tier de reputación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email (login)')),
                ('password_hash', models.CharField(max_length=255)),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
            },
        ),
    ]
