# Generated by Django 6.1.1 on 2026-09-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento_carrera',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento / Carrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(default='', max_length=100, verbose_name='Facultad'),
            preserve_default=False,
        ),
    ]
