# Generated by Django 6.1.1 on 2026-09-23 23:28

import apps.usuarios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_rol_a_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=apps.usuarios.models.rol_prestatario_por_defecto, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol'),
        ),
    ]