# Generated by Django 6.1.1 on 2026-09-27 04:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('codigo_inventario', models.CharField(help_text='Identificador único del material en el inventario.', max_length=30, unique=True, verbose_name='Código de inventario')),
                ('tipo', models.CharField(choices=[('equipo', 'Equipo'), ('libro', 'Libro'), ('objeto', 'Objeto')], max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_mantenimiento', 'En Mantenimiento'), ('reservado', 'Reservado'), ('prestado', 'Prestado')], default='disponible', max_length=20)),
                ('es_alto_valor', models.BooleanField(default=False, help_text='Los equipos de alto valor exigen garantía al prestarlos (RN05).', verbose_name='Es de alto valor')),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('estado_fisico', models.CharField(blank=True, default='', max_length=50, verbose_name='Estado físico')),
                ('foto_url', models.URLField(blank=True, default='', max_length=300)),
                ('tier_minimo_requerido', models.CharField(choices=[('avanzado', 'Avanzado'), ('estandar', 'Estándar'), ('restringido', 'Restringido')], default='estandar', max_length=20, verbose_name='Tier mínimo requerido')),
                ('bonificacion_tiempo', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Bonificación por entrega a tiempo')),
                ('deduccion_tardanza', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Deducción por tardanza (por día)')),
                ('deduccion_dano_parcial', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Deducción por daño parcial')),
                ('deduccion_dano_total', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Deducción por daño total')),
                ('costo_reparacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de reparación')),
                ('costo_reposicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de reposición')),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades registradas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='material_estado_idx'), models.Index(fields=['tipo'], name='material_tipo_idx')],
            },
        ),
    ]
