# Generated by Django 6.1.1 on 2026-09-27 20:06

import apps.inventario.models
import apps.inventario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='material',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen del material: JPG, PNG o WEBP, hasta 5 MB.', upload_to=apps.inventario.models.ruta_foto, validators=[apps.inventario.validators.validar_foto], verbose_name='Foto del material'),
        ),
    ]
