# Generated by Django 6.1.1 on 2026-10-09 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_material_foto_url_material_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_ejemplar', models.CharField(help_text='Identificador único de la copia física (ej. LIB-CLRS-01).', max_length=50, unique=True, verbose_name='Código de ejemplar / patrimonial')),
                ('numero_serie', models.CharField(blank=True, default='', help_text='Número de serie del fabricante si aplica a esta unidad.', max_length=80, verbose_name='Número de serie')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('prestado', 'Prestado'), ('en_mantenimiento', 'En Mantenimiento'), ('de_baja', 'De Baja')], default='disponible', max_length=20, verbose_name='Estado de la instancia')),
                ('estado_fisico', models.CharField(blank=True, default='Operativo', help_text='Condición física de este ejemplar (ej. Excelente, Bueno, Desgaste leve).', max_length=100, verbose_name='Estado físico')),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas específicas sobre esta copia (accesorios, defectos, etc.).', verbose_name='Observaciones')),
                ('ubicacion', models.CharField(blank=True, default='', help_text='Estante, repisa o lugar donde se guarda en almacén.', max_length=100, verbose_name='Ubicación física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='inventario.material', verbose_name='Material al que pertenece')),
            ],
            options={
                'verbose_name': 'Instancia de Material',
                'verbose_name_plural': 'Instancias de Material',
                'ordering': ['codigo_ejemplar'],
                'indexes': [models.Index(fields=['material', 'estado'], name='instancia_mat_est_idx'), models.Index(fields=['codigo_ejemplar'], name='instancia_cod_idx')],
            },
        ),
    ]
